### ISSUE TITLE
Wont open on Iphone SE (first gen) 

### ISSUE THREAD

**Issue by datboi2008** [Helloyunho/real-card#2]
Im on IOS ver 14.7.1 and have jailbreaked. When I install it with troll store, it crashes whenever I open it. If this is normal, I have still not got it to work with spice tools. Help would be much appreciated.

**Comment by Helloyunho** [comment]
Hello!

Sadly, iPhone SE 1st gen is not supported. iPhone 8 or newer is required.

But... it should at least not crash though.
Can you send me the crash log in Settings -> Privacy -> Analytics -> Analytics Data -> Real-Card related logs?

**Comment by datboi2008** [comment]
[Real Card-2023-08-14-222116.txt](https://github.com/Helloyunho/real-card/files/12344687/Real.Card-2023-08-14-222116.txt)

Heres the log

Thats a bummer that the 1st gen doesn't work. I saw that it had NFC but I looked deeper and its not able to be used by developers and only used by apple pay.

**Comment by Helloyunho** [comment]
> [Real Card-2023-08-14-222116.txt](https://github.com/Helloyunho/real-card/files/12344687/Real.Card-2023-08-14-222116.txt)
> 
> Heres the log
> 
> Thats a bummer that the 1st gen doesn't work. I saw that it had NFC but I looked deeper and its not able to be used by developers and only used by apple pay.

Thanks for the log!

Seems like iOS 14 doesn't have Swift concurrency(async/await) support. I should've mention this on README.md.
